data_pipeline_with_dbt_snowflake:
  outputs:
    dev:
      account: 
      database:
      insecure_mode: 
      password: 
      role: 
      schema: 
      type: 
      user: 
      warehouse: 
  target: 
